from lib import async_proxy_crawler, async_crawler


def scraper(html):
    return 'ok'


if __name__ == '__main__':
    res_list = async_proxy_crawler.run([
        'https://www.w3schools.com/python/python_tuples.asp',
        'https://www.w3schools.com/python/python_intro.asp',
        'https://www.w3schools.com/python/python_getstarted.asp',
        'https://www.w3schools.com/python/python_syntax.asp',
        'https://www.w3schools.com/python/python_comments.asp',
        'https://www.w3schools.com/python/python_variables.asp',
        'https://www.w3schools.com/python/python_tuples.asp',
        'https://www.w3schools.com/python/python_intro.asp',
        'https://www.w3schools.com/python/python_getstarted.asp',
        'https://www.w3schools.com/python/python_syntax.asp',
        'https://www.w3schools.com/python/python_comments.asp',
        'https://www.w3schools.com/python/python_variables.asp',
        'https://www.w3schools.com/python/python_tuples.asp',
        'https://www.w3schools.com/python/python_intro.asp',
        'https://www.w3schools.com/python/python_getstarted.asp',
        'https://www.w3schools.com/python/python_syntax.asp',
        'https://www.w3schools.com/python/python_comments.asp',
        'https://www.w3schools.com/python/python_variables.asp',
        'https://www.w3schools.com/python/python_tuples.asp',
        'https://www.w3schools.com/python/python_intro.asp',
        'https://www.w3schools.com/python/python_getstarted.asp',
        'https://www.w3schools.com/python/python_syntax.asp',
        'https://www.w3schools.com/python/python_comments.asp',
        'https://www.w3schools.com/python/python_variables.asp',
        'https://www.w3schools.com/python/python_tuples.asp',
        'https://www.w3schools.com/python/python_intro.asp',
        'https://www.w3schools.com/python/python_getstarted.asp',
        'https://www.w3schools.com/python/python_syntax.asp',
        'https://www.w3schools.com/python/python_comments.asp',
        'https://www.w3schools.com/python/python_variables.asp',
        'https://www.w3schools.com/python/python_tuples.asp',
        'https://www.w3schools.com/python/python_intro.asp',
        'https://www.w3schools.com/python/python_getstarted.asp',
        'https://www.w3schools.com/python/python_syntax.asp',
        'https://www.w3schools.com/python/python_comments.asp',
        'https://www.w3schools.com/python/python_variables.asp',
        'https://www.w3schools.com/python/python_tuples.asp',
        'https://www.w3schools.com/python/python_intro.asp',
        'https://www.w3schools.com/python/python_getstarted.asp',
        'https://www.w3schools.com/python/python_syntax.asp',
        'https://www.w3schools.com/python/python_comments.asp',
        'https://www.w3schools.com/python/python_variables.asp',
        'https://www.w3schools.com/python/python_tuples.asp',
        'https://www.w3schools.com/python/python_intro.asp',
        'https://www.w3schools.com/python/python_getstarted.asp',
        'https://www.w3schools.com/python/python_syntax.asp',
        'https://www.w3schools.com/python/python_comments.asp',
        'https://www.w3schools.com/python/python_variables.asp',
        'https://www.w3schools.com/python/python_tuples.asp',
        'https://www.w3schools.com/python/python_intro.asp',
        'https://www.w3schools.com/python/python_getstarted.asp',
        'https://www.w3schools.com/python/python_syntax.asp',
        'https://www.w3schools.com/python/python_comments.asp',
        'https://www.w3schools.com/python/python_variables.asp',
        'https://www.w3schools.com/python/python_tuples.asp',
        'https://www.w3schools.com/python/python_intro.asp',
        'https://www.w3schools.com/python/python_getstarted.asp',
        'https://www.w3schools.com/python/python_syntax.asp',
        'https://www.w3schools.com/python/python_comments.asp',
        'https://www.w3schools.com/python/python_variables.asp',
        'https://www.w3schools.com/python/python_tuples.asp',
        'https://www.w3schools.com/python/python_intro.asp',
        'https://www.w3schools.com/python/python_getstarted.asp',
        'https://www.w3schools.com/python/python_syntax.asp',
        'https://www.w3schools.com/python/python_comments.asp',
        'https://www.w3schools.com/python/python_variables.asp',
        'https://www.w3schools.com/python/python_tuples.asp',
        'https://www.w3schools.com/python/python_intro.asp',
        'https://www.w3schools.com/python/python_getstarted.asp',
        'https://www.w3schools.com/python/python_syntax.asp',
        'https://www.w3schools.com/python/python_comments.asp',
        'https://www.w3schools.com/python/python_variables.asp',
        'https://www.w3schools.com/python/python_tuples.asp',
        'https://www.w3schools.com/python/python_intro.asp',
        'https://www.w3schools.com/python/python_getstarted.asp',
        'https://www.w3schools.com/python/python_syntax.asp',
        'https://www.w3schools.com/python/python_comments.asp',
        'https://www.w3schools.com/python/python_variables.asp',
        'https://www.w3schools.com/python/python_tuples.asp',
        'https://www.w3schools.com/python/python_intro.asp',
        'https://www.w3schools.com/python/python_getstarted.asp',
        'https://www.w3schools.com/python/python_syntax.asp',
        'https://www.w3schools.com/python/python_comments.asp',
        'https://www.w3schools.com/python/python_variables.asp',
        'https://www.w3schools.com/python/python_tuples.asp',
        'https://www.w3schools.com/python/python_intro.asp',
        'https://www.w3schools.com/python/python_getstarted.asp',
        'https://www.w3schools.com/python/python_syntax.asp',
        'https://www.w3schools.com/python/python_comments.asp',
        'https://www.w3schools.com/python/python_variables.asp',
    ], scraper)

    print(res_list)
